### ISSUE TITLE
Question about RBL's

### ISSUE THREAD

**Issue by MarceloPedra** [neo22s/emailvalidator#1]
Hello, I found your project linked from an entry in Sendy Forum. I'm looking for a script like your by my only worry is if using it will be accepted or rejected by great players like hotmail/yahoo/gmail when it comes to validate lots (hundreds/thousands) of emails. 

Do you know any reference or by own experience if the IP address hosting this script may be blocked by ESP's or even added to any RBL?

Thanks in advance!

**Comment by neo22s** [comment]
Uses DNS to check if there's MX records...they should not ban you for that at all.... the DNS system is designed for such queries ;)
