### ISSUE TITLE
Validation is true?

### ISSUE THREAD

**Issue by tomoeuehara** [neo22s/emailvalidator#2]
Good day,
When I tested your code, it only checks for valid MX-Records without really checking whether it's really exist or not.
You can input random non exist email address, like "120397sakj1487df@gmail.com" and the json will still returns true.
So in summary, this isn't a true email validator.

**Comment by neo22s** [comment]
Theres only 1 way to validate that.

Sending an email to the email address and check if they opened it. So no we do not do that , and never have claimed we do.

Also we do not only check MX. please read https://github.com/neo22s/emailvalidator/blob/master/emailvalidator.php#L21

https://mailjagger.com/
